-- supabase/migrations/0005_seed_tenant.sql
-- v1 seeds exactly one restaurant (the founder's friend's ramen shop).
-- Membership is NOT seeded here — the founder creates the friend's user via the
-- Supabase Dashboard (D-10) and the custom access token hook injects restaurant_id
-- on first login. Forkers replace the name and timezone with their own values.
--
-- The `where not exists` clause makes this migration idempotent: re-running against
-- an already-seeded project is a no-op. The id is generated by gen_random_uuid()
-- from the restaurants table default — no hardcoded UUID literal.

insert into public.restaurants (name, timezone)
select 'Ramen Shop (v1 tenant)', 'Europe/Berlin'
where not exists (select 1 from public.restaurants);
